import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import "@smastrom/react-rating/style.css";
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";

export const metadata: Metadata = {
  title: "Baby Care Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={` bg-gradient-to-t from-[#fbc2eb] to-[#a6c1ee] min-h-screen`}
        className={`bg-[#E3E6E6] min-h-screen`}
      >
        <ReduxProvider>{children}</ReduxProvider>
        <Toaster position="top-center" duration={3000} />
      </body>
    </html>
  );
}
